# Generated by Django 2.2.3 on 2019-11-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NO', models.IntegerField(unique=True)),
                ('PRODUCT_NAME', models.CharField(max_length=30)),
                ('PRODUCT_PRICE', models.FloatField()),
                ('PRODUCT_QUANTITY', models.IntegerField()),
                ('Merchant_Id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app_admin.MerchantModel')),
            ],
        ),
    ]
