# Generated by Django 2.2.3 on 2019-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='PRODUCT_NO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
