# Generated by Django 2.2.3 on 2019-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_auto_20191110_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='PRODUCT_NO',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
